spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  #redis:
    #sentinel: #集群 配置哨兵 一般默认是mymaster名字
      #master: mymaster  #哨兵是多个所以配置多个 三个哨兵的ip和端口 (连接哨兵然后哨兵连接redis)
      #nodes: 192.168.92.128:26380,192.168.92.128:26381,192.168.92.128:26382

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: secret #JWT加解密使用的密钥
  expiration: 3600 #JWT的超期限时间秒(60分钟)
  tokenHead: tokenHead  #JWT负载中拿到开头

#redis:
  #redisTime: 60 #redis设置缓存时间 为10秒

secure:
  ignored:
    urls: #安全路径白名单
      /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com  # oss对外服务的访问域名
    accessKeyId: LTAI4FeiEuYzTUjp7AuNKEo2 # 访问身份验证中用到用户标识
    accessKeySecret: XUEyNCZVWd7jTpKdlF1RNdO0cuuijc # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: server-test1 # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: images/ # 上传文件夹路径前缀


logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug